on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        
      - name: Build and push Docker images
        # You may pin to the exact commit or the version.
        # uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f
        uses: docker/build-push-action@v7.1.0
        with:
          context: .
          push: true
          tags: ghcr.io/hugespaceship/vitasdk:latest
